
server:
  port: 8080

spring:
  application:
    name: Camp_Reserve
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus
    hikari:
      username: root
      password: admin1234
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 74c81051576be2126396ca67ae865bbf
            client-secret: jL5tYa5A9wGyEHTFLuqzFmpRoTYEdUvg
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


token:
  expiration_time: 43200000
  secret: sRNKzg51ZkMoNu1PvSosY6xGYPfXnk23xYxLuMNryyQRY-rwKTLqbSoOaSGeT-Ypj2z7Lj3vBhC5zC0XxrmXUA==

# Swagger UI 설정 추가
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method



